### ISSUE TITLE
Evaluation on given checkpoint fials issue

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/ovon#1]
[ovon-ver-995995.log](https://github.com/user-attachments/files/17528412/ovon-ver-995995.log)
Config [file](https://github.com/AnandSingh-0619/ovon/blob/anand_dev/my_scripts/eval/eval_daggerl_tf.sh)
Weight file is from the link provided on repo.
Tried to use the same config that was used for training.

`  File "/srv/cvmlp-lab/flash1/asingh3064/envs/ovon/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/srv/cvmlp-lab/flash1/asingh3064/envs/ovon/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/coc/testnvme/asingh3064/ovon/ovon/run.py", line 273, in <module>
    main()
  File "/coc/testnvme/asingh3064/ovon/ovon/run.py", line 136, in main
    execute_exp(config, args.run_type)
  File "/coc/testnvme/asingh3064/ovon/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 83, in execute_exp
    trainer.eval()
  File "/coc/testnvme/asingh3064/ovon/habitat-lab/habitat-baselines/habitat_baselines/common/base_trainer.py", line 152, in eval
    checkpoint_index=prev_ckpt_ind,
  File "/coc/testnvme/asingh3064/ovon/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 1065, in _eval_checkpoint
    deterministic=False,
  File "/coc/testnvme/asingh3064/ovon/ovon/algos/dagger.py", line 270, in act
    observations, rnn_hidden_states, prev_actions, masks
  File "/srv/cvmlp-lab/flash1/asingh3064/envs/ovon/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/coc/testnvme/asingh3064/ovon/ovon/models/transformer_policy.py", line 131, in forward
    rnn_build_seq_info,
  File "/coc/testnvme/asingh3064/ovon/ovon/models/clip_policy.py", line 498, in forward
    out = torch.cat(x, dim=1)`

**Comment by yusufali98** [comment]
The evaluation will always use the config that is stored in the checkpoint file so supplying a new config through commandline doesnt make a difference.

Based on the logs, it seems the evaluation is being run on the training episodes due to the following:
`  0%|          | 0/6911470 [00:00<?, ?it/s]Traceback (most recent call last):
`
Can you put a breakpoint [here](https://github.com/facebookresearch/habitat-lab/blob/v0.2.3/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py#L964) and closely inspect the config ? Specifically, whats the `habitat.dataset.data_path` ?

**Comment by yusufali98** [comment]
Also it seems like there is a discrepancy in the `num_environments`
The `num_envs` in the [config file supplied through sbatch script](https://github.com/AnandSingh-0619/ovon/blob/anand_dev/config/experiments/transformer_dagger.yaml#L56) is 32
But according to the logs, the resume state config has `num_envs` 16 which you can search for in the config printed in the log you shared
So the policy code is being intialized with `num_envs=16` but the config file supplied through sbatch script has `num_envs=32`. I think you can fix this issue by setting [this](https://github.com/AnandSingh-0619/ovon/blob/anand_dev/config/experiments/transformer_dagger.yaml#L56) to 16

**Comment by AnandSingh-0619** [comment]
Evaluation fixed and will be merged with this [pull request](https://github.com/AnandSingh-0619/ovon/pull/3)
Check change log of this PR for file changes
