### ISSUE TITLE
cudnn lib issue

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/ovon#4]
`Traceback (most recent call last):`
 ` File "<stdin>", line 1, in <module>`
  `File "/nethome/asingh3064/.local/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py", line 82, in version`
 `   if not _init():`
`  File "/nethome/asingh3064/.local/lib/python3.8/site-packages/torch/backends/cudnn/__init__.py", line 70, in _init`
`   raise RuntimeError(base_error_msg)`
`RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (8, 9, 2) but found runtime version (8, 4, 0). PyTorch` `already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN. `

**Comment by AnandSingh-0619** [comment]
`You said:
>>> import torch

>>> print(torch.cuda.is_available())
True
>>> # Check CUDA version
>>> print("CUDA version:", torch.version.cuda)
CUDA version: 12.1
>>> 
>>> # Check cuDNN version
>>> print("cuDNN version:", torch.backends.cudnn.version())
Could not load library libcudnn_ops_infer.so.8. Error: libcublas.so.11: cannot open shared object file: No such file or directory
Aborted (core dumped)`

**Comment by AnandSingh-0619** [comment]
Solved by setting up new conda env with python 3.8
